# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        echo '${{ secrets.ZOD_COOKIES }}' > ~/zod.cookies.json
        echo '${{ secrets.TSDM_COOKIES }}' > ~/tsdm.cookies.json
        echo '${{ secrets.AWS_CONFIG }}' > ~/.aws/config
        echo '${{ secrets.AWS_CREDENTIALS }}' > ~/.aws/credentials
        python checkin.py -t zod ~/zod.cookies.json -hook https://tg-msg-sender.herokuapp.com/ -cf
        python checkin.py -t tsdm ~/tsdm.cookies.json -hook https://tg-msg-sender.herokuapp.com/ 
